# from django.core.exceptions import ValidationError


class PaymentValidator:
    def __init__(self): ...

    def __call__(self):
        return True


class CheckValidator:
    def __init__(self): ...

    def __call__(self):
        return True
